<a href="https://colab.research.google.com/github/SHANUKRISHNAN/SHANU/blob/main/Another_copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset("titanic")

In [3]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [5]:
df.shape

(891, 15)

In [7]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [9]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [10]:
df.isnull().sum()   # checking missing values

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [11]:
# drop missing value
df=df.drop(columns=["deck"])

In [12]:
df.dropna(subset=['embarked','embark_town'],inplace=True)
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64


In [ ]:
# Fill missing numerical values with mean

In [ ]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [ ]:
print(df.isnull().sum())


survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64


In [ ]:
# creating and modifying columns

In [ ]:
df['family_size']=df['sibsp']+df['parch']

In [ ]:
df['age_group']=np.where(df['age']<18,"child","Adult")

In [ ]:
df['fare_per_person']=df['fare']/(df['family_size']+1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype   
---  ------           --------------  -----   
 0   survived         889 non-null    int64   
 1   pclass           889 non-null    int64   
 2   sex              889 non-null    object  
 3   age              889 non-null    float64 
 4   sibsp            889 non-null    int64   
 5   parch            889 non-null    int64   
 6   fare             889 non-null    float64 
 7   embarked         889 non-null    object  
 8   class            889 non-null    category
 9   who              889 non-null    object  
 10  adult_male       889 non-null    bool    
 11  embark_town      889 non-null    object  
 12  alive            889 non-null    object  
 13  alone            889 non-null    bool    
 14  age_group        889 non-null    object  
 15  family_size      889 non-null    int64   
 16  fare_per_person  889 non-null    float64 
dtypes:

In [ ]:
df.isnull().sum()   # checking missing values

survived           0
pclass             0
sex                0
age                0
sibsp              0
parch              0
fare               0
embarked           0
class              0
who                0
adult_male         0
embark_town        0
alive              0
alone              0
age_group          0
family_size        0
fare_per_person    0
dtype: int64

In [ ]:
# rename and delete columns

In [ ]:
df.rename(columns={'pclass':'Passenger_Class'},inplace=True)  # orginal df will be changed when inplace =True

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype   
---  ------           --------------  -----   
 0   survived         889 non-null    int64   
 1   Passenger_Class  889 non-null    int64   
 2   sex              889 non-null    object  
 3   age              889 non-null    float64 
 4   sibsp            889 non-null    int64   
 5   parch            889 non-null    int64   
 6   fare             889 non-null    float64 
 7   embarked         889 non-null    object  
 8   class            889 non-null    category
 9   who              889 non-null    object  
 10  adult_male       889 non-null    bool    
 11  embark_town      889 non-null    object  
 12  alive            889 non-null    object  
 13  alone            889 non-null    bool    
 14  age_group        889 non-null    object  
 15  family_size      889 non-null    int64   
 16  fare_per_person  889 non-null    float64 
dtypes:

In [ ]:
df

survived  Passenger_Class     sex        age  sibsp  parch     fare  \
0           0                3    male  22.000000      1      0   7.2500   
1           1                1  female  38.000000      1      0  71.2833   
2           1                3  female  26.000000      0      0   7.9250   
3           1                1  female  35.000000      1      0  53.1000   
4           0                3    male  35.000000      0      0   8.0500   
..        ...              ...     ...        ...    ...    ...      ...   
886         0                2    male  27.000000      0      0  13.0000   
887         1                1  female  19.000000      0      0  30.0000   
888         0                3  female  29.642093      1      2  23.4500   
889         1                1    male  26.000000      0      0  30.0000   
890         0                3    male  32.000000      0      0   7.7500   

    embarked   class    who  adult_male  embark_town alive  alone age_group  \
0          S   Third    man        True  Southampton    no  False     Adult   
1          C   First  woman       False    Cherbourg   yes  False     Adult   
2          S   Third  woman       False  Southampton   yes   True     Adult   
3          S   First  woman       False  Southampton   yes  False     Adult   
4          S   Third    man        True  Southampton    no   True     Adult   
..       ...     ...    ...         ...          ...   ...    ...       ...   
886        S  Second    man        True  Southampton    no   True     Adult   
887        S   First  woman       False  Southampton   yes   True     Adult   
888        S   Third  woman       False  Southampton    no  False     Adult   
889        C   First    man        True    Cherbourg   yes   True     Adult   
890        Q   Third    man        True   Queenstown    no   True     Adult   

     family_size  fare_per_person  
0              1          3.62500  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
4              0          8.05000  
..           ...              ...  
886            0         13.00000  
887            0         30.00000  
888            3          5.86250  
889            0         30.00000  
890            0          7.75000  

[889 rows x 17 columns]

In [ ]:
# Filtering and conditional selection

In [ ]:
df['age'].mean()

np.float64(29.642092696629216)

In [ ]:
df[df['age']>df['age'].mean()]

survived  Passenger_Class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
3           1                1  female  35.0      1      0  53.1000        S   
4           0                3    male  35.0      0      0   8.0500        S   
6           0                1    male  54.0      0      0  51.8625        S   
11          1                1  female  58.0      0      0  26.5500        S   
..        ...              ...     ...   ...    ...    ...      ...      ...   
873         0                3    male  47.0      0      0   9.0000        S   
879         1                1  female  56.0      0      1  83.1583        C   
881         0                3    male  33.0      0      0   7.8958        S   
885         0                3  female  39.0      0      5  29.1250        Q   
890         0                3    male  32.0      0      0   7.7500        Q   

     class    who  adult_male  embark_town alive  alone age_group  \
1    First  woman       False    Cherbourg   yes  False     Adult   
3    First  woman       False  Southampton   yes  False     Adult   
4    Third    man        True  Southampton    no   True     Adult   
6    First    man        True  Southampton    no   True     Adult   
11   First  woman       False  Southampton   yes   True     Adult   
..     ...    ...         ...          ...   ...    ...       ...   
873  Third    man        True  Southampton    no   True     Adult   
879  First  woman       False    Cherbourg   yes  False     Adult   
881  Third    man        True  Southampton    no   True     Adult   
885  Third  woman       False   Queenstown    no  False     Adult   
890  Third    man        True   Queenstown    no   True     Adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
4              0         8.050000  
6              0        51.862500  
11             0        26.550000  
..           ...              ...  
873            0         9.000000  
879            1        41.579150  
881            0         7.895800  
885            5         4.854167  
890            0         7.750000  

[328 rows x 17 columns]

In [ ]:
# Female passengers in first class

In [ ]:
df[(df['sex']=='female') & (df['Passenger_Class']==1)]

survived  Passenger_Class     sex        age  sibsp  parch      fare  \
1           1                1  female  38.000000      1      0   71.2833   
3           1                1  female  35.000000      1      0   53.1000   
11          1                1  female  58.000000      0      0   26.5500   
31          1                1  female  29.642093      1      0  146.5208   
52          1                1  female  49.000000      1      0   76.7292   
..        ...              ...     ...        ...    ...    ...       ...   
856         1                1  female  45.000000      1      1  164.8667   
862         1                1  female  48.000000      0      0   25.9292   
871         1                1  female  47.000000      1      1   52.5542   
879         1                1  female  56.000000      0      1   83.1583   
887         1                1  female  19.000000      0      0   30.0000   

    embarked  class    who  adult_male  embark_town alive  alone age_group  \
1          C  First  woman       False    Cherbourg   yes  False     Adult   
3          S  First  woman       False  Southampton   yes  False     Adult   
11         S  First  woman       False  Southampton   yes   True     Adult   
31         C  First  woman       False    Cherbourg   yes  False     Adult   
52         C  First  woman       False    Cherbourg   yes  False     Adult   
..       ...    ...    ...         ...          ...   ...    ...       ...   
856        S  First  woman       False  Southampton   yes  False     Adult   
862        S  First  woman       False  Southampton   yes   True     Adult   
871        S  First  woman       False  Southampton   yes  False     Adult   
879        C  First  woman       False    Cherbourg   yes  False     Adult   
887        S  First  woman       False  Southampton   yes   True     Adult   

     family_size  fare_per_person  
1              1        35.641650  
3              1        26.550000  
11             0        26.550000  
31             1        73.260400  
52             1        38.364600  
..           ...              ...  
856            2        54.955567  
862            0        25.929200  
871            2        17.518067  
879            1        41.579150  
887            0        30.000000  

[92 rows x 17 columns]

In [ ]:
df[(df['survived']==1)]

survived  Passenger_Class     sex   age  sibsp  parch     fare embarked  \
1           1                1  female  38.0      1      0  71.2833        C   
2           1                3  female  26.0      0      0   7.9250        S   
3           1                1  female  35.0      1      0  53.1000        S   
8           1                3  female  27.0      0      2  11.1333        S   
9           1                2  female  14.0      1      0  30.0708        C   
..        ...              ...     ...   ...    ...    ...      ...      ...   
875         1                3  female  15.0      0      0   7.2250        C   
879         1                1  female  56.0      0      1  83.1583        C   
880         1                2  female  25.0      0      1  26.0000        S   
887         1                1  female  19.0      0      0  30.0000        S   
889         1                1    male  26.0      0      0  30.0000        C   

      class    who  adult_male  embark_town alive  alone age_group  \
1     First  woman       False    Cherbourg   yes  False     Adult   
2     Third  woman       False  Southampton   yes   True     Adult   
3     First  woman       False  Southampton   yes  False     Adult   
8     Third  woman       False  Southampton   yes  False     Adult   
9    Second  child       False    Cherbourg   yes  False     child   
..      ...    ...         ...          ...   ...    ...       ...   
875   Third  child       False    Cherbourg   yes   True     child   
879   First  woman       False    Cherbourg   yes  False     Adult   
880  Second  woman       False  Southampton   yes  False     Adult   
887   First  woman       False  Southampton   yes   True     Adult   
889   First    man        True    Cherbourg   yes   True     Adult   

     family_size  fare_per_person  
1              1         35.64165  
2              0          7.92500  
3              1         26.55000  
8              2          3.71110  
9              1         15.03540  
..           ...              ...  
875            0          7.22500  
879            1         41.57915  
880            1         13.00000  
887            0         30.00000  
889            0         30.00000  

[340 rows x 17 columns]

In [ ]:
# GroupBy and statistical thinking

In [ ]:
df.groupby('sex')['survived'].mean()

sex
female    0.740385
male      0.188908
Name: survived, dtype: float64

In [ ]:
# Average fare by class

In [ ]:
df.groupby('class')['fare'].mean()

/tmp/ipython-input-4105422611.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].mean()


class
First     84.193516
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [ ]:
# which var are highly correlated

In [ ]:
df.corr(numeric_only=True)

survived  Passenger_Class       age     sibsp     parch  \
survived         1.000000        -0.335549 -0.074513 -0.034040  0.083151   
Passenger_Class -0.335549         1.000000 -0.328256  0.081656  0.016824   
age             -0.074513        -0.328256  1.000000 -0.231908 -0.178013   
sibsp           -0.034040         0.081656 -0.231908  1.000000  0.414542   
parch            0.083151         0.016824 -0.178013  0.414542  1.000000   
fare             0.255290        -0.548193  0.088780  0.160887  0.217532   
adult_male      -0.555520         0.090098  0.258793 -0.255401 -0.351945   
alone           -0.206207         0.138553  0.177445 -0.584186 -0.583112   
family_size      0.018277         0.064221 -0.247459  0.890654  0.782988   
fare_per_person  0.217902        -0.482024  0.136787 -0.093211 -0.067422   

                     fare  adult_male     alone  family_size  fare_per_person  
survived         0.255290   -0.555520 -0.206207     0.018277         0.217902  
Passenger_Class -0.548193    0.090098  0.138553     0.064221        -0.482024  
age              0.088780    0.258793  0.177445    -0.247459         0.136787  
sibsp            0.160887   -0.255401 -0.584186     0.890654        -0.093211  
parch            0.217532   -0.351945 -0.583112     0.782988        -0.067422  
fare             1.000000   -0.179851 -0.274079     0.218658         0.840902  
adult_male      -0.179851    1.000000  0.407992    -0.350419        -0.078503  
alone           -0.274079    0.407992  1.000000    -0.690654         0.042706  
family_size      0.218658   -0.350419 -0.690654     1.000000        -0.097399  
fare_per_person  0.840902   -0.078503  0.042706    -0.097399         1.000000

In [ ]:
df1=sns.load_dataset("tips")
df1

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [ ]:
df1.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df1.shape

(244, 7)

In [ ]:
df1.size

1708

In [ ]:
df1.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df1['total_bill'].mean()

np.float64(19.78594262295082)

In [ ]:
df1['tip'].mean()

np.float64(2.99827868852459)

In [ ]:
df1['tip'].median()

2.9

In [ ]:
df1['Tip_percentage']=(df1['tip']/df1['total_bill'])*100
df1

total_bill   tip     sex smoker   day    time  size  Tip_percentage  \
0         16.99  1.01  Female     No   Sun  Dinner     2        5.944673   
1         10.34  1.66    Male     No   Sun  Dinner     3       16.054159   
2         21.01  3.50    Male     No   Sun  Dinner     3       16.658734   
3         23.68  3.31    Male     No   Sun  Dinner     2       13.978041   
4         24.59  3.61  Female     No   Sun  Dinner     4       14.680765   
..          ...   ...     ...    ...   ...     ...   ...             ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697   
240       27.18  2.00  Female    Yes   Sat  Dinner     2        7.358352   
241       22.67  2.00    Male    Yes   Sat  Dinner     2        8.822232   
242       17.82  1.75    Male     No   Sat  Dinner     2        9.820426   
243       18.78  3.00  Female     No  Thur  Dinner     2       15.974441   

     high_spender  
0               0  
1               0  
2               1  
3               1  
4               1  
..            ...  
239             1  
240             1  
241             1  
242             0  
243             0  

[244 rows x 9 columns]

In [ ]:
df1['high_spender']=np.where(df1['total_bill']>df1['total_bill'].mean(),1,0)
df1

total_bill   tip     sex smoker   day    time  size  Tip_percentage  \
0         16.99  1.01  Female     No   Sun  Dinner     2        5.944673   
1         10.34  1.66    Male     No   Sun  Dinner     3       16.054159   
2         21.01  3.50    Male     No   Sun  Dinner     3       16.658734   
3         23.68  3.31    Male     No   Sun  Dinner     2       13.978041   
4         24.59  3.61  Female     No   Sun  Dinner     4       14.680765   
..          ...   ...     ...    ...   ...     ...   ...             ...   
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697   
240       27.18  2.00  Female    Yes   Sat  Dinner     2        7.358352   
241       22.67  2.00    Male    Yes   Sat  Dinner     2        8.822232   
242       17.82  1.75    Male     No   Sat  Dinner     2        9.820426   
243       18.78  3.00  Female     No  Thur  Dinner     2       15.974441   

     high_spender  
0               0  
1               0  
2               1  
3               1  
4               1  
..            ...  
239             1  
240             1  
241             1  
242             0  
243             0  

[244 rows x 9 columns]

In [ ]:
df1.dtypes

total_bill         float64
tip                float64
sex               category
smoker            category
day               category
time              category
size                 int64
Tip_percentage        bool
high_spender         int64
dtype: object

In [ ]:
df1[df1['total_bill']>30]

total_bill    tip     sex smoker   day    time  size  Tip_percentage  \
11        35.26   5.00  Female     No   Sun  Dinner     4           False   
23        39.42   7.58    Male     No   Sat  Dinner     4           False   
39        31.27   5.00    Male     No   Sat  Dinner     3           False   
44        30.40   5.60    Male     No   Sun  Dinner     4           False   
47        32.40   6.00    Male     No   Sun  Dinner     4           False   
52        34.81   5.20  Female     No   Sun  Dinner     4           False   
56        38.01   3.00    Male    Yes   Sat  Dinner     4           False   
59        48.27   6.73    Male     No   Sat  Dinner     4           False   
83        32.68   5.00    Male    Yes  Thur   Lunch     2           False   
85        34.83   5.17  Female     No  Thur   Lunch     4           False   
95        40.17   4.73    Male    Yes   Fri  Dinner     4           False   
102       44.30   2.50  Female    Yes   Sat  Dinner     3           False   
112       38.07   4.00    Male     No   Sun  Dinner     3           False   
141       34.30   6.70    Male     No  Thur   Lunch     6           False   
142       41.19   5.00    Male     No  Thur   Lunch     5           False   
156       48.17   5.00    Male     No   Sun  Dinner     6           False   
167       31.71   4.50    Male     No   Sun  Dinner     4           False   
170       50.81  10.00    Male    Yes   Sat  Dinner     3           False   
173       31.85   3.18    Male    Yes   Sun  Dinner     2           False   
175       32.90   3.11    Male    Yes   Sun  Dinner     2           False   
179       34.63   3.55    Male    Yes   Sun  Dinner     2           False   
180       34.65   3.68    Male    Yes   Sun  Dinner     4           False   
182       45.35   3.50    Male    Yes   Sun  Dinner     3           False   
184       40.55   3.00    Male    Yes   Sun  Dinner     2           False   
187       30.46   2.00    Male    Yes   Sun  Dinner     5           False   
197       43.11   5.00  Female    Yes  Thur   Lunch     4           False   
207       38.73   3.00    Male    Yes   Sat  Dinner     4           False   
210       30.06   2.00    Male    Yes   Sat  Dinner     3           False   
212       48.33   9.00    Male     No   Sat  Dinner     4           False   
219       30.14   3.09  Female    Yes   Sat  Dinner     4           False   
237       32.83   1.17    Male    Yes   Sat  Dinner     2           False   
238       35.83   4.67  Female     No   Sat  Dinner     3           False   

     high_spender  
11              1  
23              1  
39              1  
44              1  
47              1  
52              1  
56              1  
59              1  
83              1  
85              1  
95              1  
102             1  
112             1  
141             1  
142             1  
156             1  
167             1  
170             1  
173             1  
175             1  
179             1  
180             1  
182             1  
184             1  
187             1  
197             1  
207             1  
210             1  
212             1  
219             1  
237             1  
238             1

In [ ]:
(df1['Tip_percentage']>20).sum()

np.int64(39)

In [ ]:
df1[df1['Tip_percentage']>20]

total_bill   tip     sex smoker   day    time  size  Tip_percentage  \
6          8.77  2.00    Male     No   Sun  Dinner     2       22.805017   
9         14.78  3.23    Male     No   Sun  Dinner     2       21.853857   
14        14.83  3.02  Female     No   Sun  Dinner     2       20.364127   
17        16.29  3.71    Male     No   Sun  Dinner     3       22.774708   
18        16.97  3.50  Female     No   Sun  Dinner     3       20.624632   
20        17.92  4.08    Male     No   Sat  Dinner     2       22.767857   
42        13.94  3.06    Male     No   Sun  Dinner     2       21.951220   
46        22.23  5.00    Male     No   Sun  Dinner     2       22.492128   
51        10.29  2.60  Female     No   Sun  Dinner     2       25.267250   
63        18.29  3.76    Male    Yes   Sat  Dinner     4       20.557682   
67         3.07  1.00  Female    Yes   Sat  Dinner     1       32.573290   
81        16.66  3.40    Male     No  Thur   Lunch     2       20.408163   
87        18.28  4.00    Male     No  Thur   Lunch     2       21.881838   
88        24.71  5.85    Male     No  Thur   Lunch     2       23.674626   
93        16.32  4.30  Female    Yes   Fri  Dinner     2       26.348039   
100       11.35  2.50  Female    Yes   Fri  Dinner     2       22.026432   
108       18.24  3.76    Male     No   Sat  Dinner     2       20.614035   
109       14.31  4.00  Female    Yes   Sat  Dinner     2       27.952481   
110       14.00  3.00    Male     No   Sat  Dinner     2       21.428571   
115       17.31  3.50  Female     No   Sun  Dinner     2       20.219526   
124       12.48  2.52  Female     No  Thur   Lunch     2       20.192308   
139       13.16  2.75  Female     No  Thur   Lunch     2       20.896657   
140       17.47  3.50  Female     No  Thur   Lunch     2       20.034345   
149        7.51  2.00    Male     No  Thur   Lunch     2       26.631158   
172        7.25  5.15    Male    Yes   Sun  Dinner     2       71.034483   
174       16.82  4.00    Male    Yes   Sun  Dinner     2       23.781213   
178        9.60  4.00  Female    Yes   Sun  Dinner     2       41.666667   
181       23.33  5.65    Male    Yes   Sun  Dinner     2       24.217745   
183       23.17  6.50    Male    Yes   Sun  Dinner     4       28.053517   
185       20.69  5.00    Male     No   Sun  Dinner     5       24.166264   
191       19.81  4.19  Female    Yes  Thur   Lunch     2       21.150934   
194       16.58  4.00    Male    Yes  Thur   Lunch     2       24.125452   
200       18.71  4.00    Male    Yes  Thur   Lunch     3       21.378942   
214       28.17  6.50  Female    Yes   Sat  Dinner     3       23.074192   
221       13.42  3.48  Female    Yes   Fri   Lunch     2       25.931446   
222        8.58  1.92    Male    Yes   Fri   Lunch     1       22.377622   
228       13.28  2.72    Male     No   Sat  Dinner     2       20.481928   
232       11.61  3.39    Male     No   Sat  Dinner     2       29.198966   
239       29.03  5.92    Male     No   Sat  Dinner     3       20.392697   

     high_spender  
6               0  
9               0  
14              0  
17              0  
18              0  
20              0  
42              0  
46              1  
51              0  
63              0  
67              0  
81              0  
87              0  
88              1  
93              0  
100             0  
108             0  
109             0  
110             0  
115             0  
124             0  
139             0  
140             0  
149             0  
172             0  
174             0  
178             0  
181             1  
183             1  
185             1  
191             1  
194             0  
200             0  
214             1  
221             0  
222             0  
228             0  
232             0  
239             1

In [ ]:
df1.groupby('sex')['tip'].mean()

/tmp/ipython-input-1728245740.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df1.groupby('sex')['tip'].mean()


sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [ ]:
df1.groupby('day')['total_bill'].mean()

/tmp/ipython-input-2895694602.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df1.groupby('day')['total_bill'].mean()


day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [ ]:
df1.groupby('smoker')['Tip_percentage'].mean()

/tmp/ipython-input-1790430916.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df1.groupby('smoker')['Tip_percentage'].mean()


smoker
Yes    16.319604
No     15.932846
Name: Tip_percentage, dtype: float64

In [ ]:
df1.corr(numeric_only=True)

total_bill       tip      size  Tip_percentage  high_spender
total_bill        1.000000  0.675734  0.598315       -0.338624      0.787342
tip               0.675734  1.000000  0.489299        0.342370      0.554292
size              0.598315  0.489299  1.000000       -0.142860      0.497736
Tip_percentage   -0.338624  0.342370 -0.142860        1.000000     -0.250158
high_spender      0.787342  0.554292  0.497736       -0.250158      1.000000

In [ ]:
array=np.arange(1,17).reshape((4,4))
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[arr%2==0]=-1
arr

array([ 1, -1,  3, -1,  5, -1])

In [ ]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [ ]:
a=np.mean(arr1)

In [ ]:
b=np.std(arr1)
b

np.float64(14.142135623730951)

In [ ]:
arr1[1]

np.int64(20)

In [ ]:
normalized=(arr1-a)/b
normalized

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
arr2=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[2:]


array([[7, 8, 9]])

In [ ]:
arr2[0,1]

np.int64(2)

In [ ]:
arr2[1][1]

np.int64(5)

In [ ]:
arr2[2][0]

np.int64(7)

In [ ]:
arr2[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
arr2[2:,1:]

array([[8, 9]])

In [ ]:
arr2[1,2]

np.int64(6)